;/*FB_PKG_DELIM*/

__d("CometComposerErrorRendererWithReportingFlow.react",["fbt","CometLink.react","VenusFlytrapLogging","VenusFlytrapLoggingEntrypoint","gkx","react","react-compiler-runtime","useFacebookVenusFlytrapDialog"],(function(a,b,c,d,e,f,g,h){"use strict";var i,j=i||d("react");function a(a){var b=d("react-compiler-runtime").c(8);a=a.errorMessage;var e=c("useFacebookVenusFlytrapDialog")(),f;b[0]!==e?(f=function(){d("VenusFlytrapLogging").venusFlytrapLoggingStart(c("VenusFlytrapLoggingEntrypoint").FACEBOOK_COMPOSER),e({configId:"FOR_FACEBOOK_DEFAULT",initialProduct:"composer"})},b[0]=e,b[1]=f):f=b[1];var g;b[2]===Symbol["for"]("react.memo_cache_sentinel")?(g=c("gkx")("20861")?h._(/*BTDS*/"Report a problem"):h._(/*BTDS*/"Give feedback"),b[2]=g):g=b[2];b[3]!==f?(g=j.jsx(c("CometLink.react"),{onClick:f,children:g}),b[3]=f,b[4]=g):g=b[4];b[5]!==a||b[6]!==g?(f=j.jsxs("div",{children:[a," ",g]}),b[5]=a,b[6]=g,b[7]=f):f=b[7];return f}g["default"]=a}),226);
__d("getUseDefaultErrorMessage",[],(function(a,b,c,d,e,f){"use strict";function a(a){return typeof a!=="string"?!1:/^Network request encountered error HTTP 500 HTTP_SERVER_ERROR/.test(a)||a.trim()===""}f["default"]=a}),66);
__d("CometComposerServerErrorMessage.react",["fbt","CometComposerErrorRendererWithReportingFlow.react","CometComposerInlineErrorRenderer.react","CometErrorOverlay","JSResourceForInteraction","NewsRegulationErrorMessageData","ServerHTML.react","SilenceableErrorMessageUtils","getUseDefaultErrorMessage","promiseDone","react"],(function(a,b,c,d,e,f,g,h){"use strict";var i,j=i||(i=d("react")),k=i.useRef,l=c("JSResourceForInteraction")("CometNewsRegulationDialog.react").__setRef("CometComposerServerErrorMessage.react");function a(a){var b=a.errorMetadata,e=a.icon;a=a.xstyle;var f=k(new Set());if(b==null)return null;if(d("SilenceableErrorMessageUtils").shouldHideErrorMessage(b))return null;var g=b==null?void 0:b.message;if(g==null)return null;var i=c("getUseDefaultErrorMessage")(g),m=i?h._(/*BTDS*/"Sorry, something went wrong. Try again later."):j.jsx(c("ServerHTML.react"),{blob:g,style:{display:"inline"}});i=b==null?void 0:b.code;var n=i!=null?(g=c("NewsRegulationErrorMessageData").errorCodeToRegType[i])!=null?g:null:null;if(n!=null){f.current.has(b)||(f.current.add(b),c("promiseDone")(l.load().then(function(a){d("CometErrorOverlay").injectComponent(function(b){return j.jsx(a,{errorDescription:m,onClose:function(){b()},regulationType:n})})})));return j.jsx("div",{})}return j.jsx(c("CometComposerInlineErrorRenderer.react"),{error:j.jsx(c("CometComposerErrorRendererWithReportingFlow.react"),{errorMessage:m}),icon:e,xstyle:a})}a.displayName=a.name+" [from "+f.id+"]";g["default"]=a}),226);
__d("XContentRefControllerRouteBuilder",["jsRouteBuilder"],(function(a,b,c,d,e,f,g){a=c("jsRouteBuilder")("/business/content_ref/",Object.freeze({}),void 0);b=a;g["default"]=b}),98);
__d("ContentRefComet",["XContentRefControllerRouteBuilder"],(function(a,b,c,d,e,f,g){"use strict";function a(a,b){b===void 0&&(b="DEFAULT");return c("XContentRefControllerRouteBuilder").buildURL({callsite:b,name:a})}g.get=a}),98);
__d("PrivacyMutationSourceIDContext",["react"],(function(a,b,c,d,e,f,g){"use strict";var h;a=h||d("react");b=null;c=a.createContext(b);g["default"]=c}),98);
__d("PrivacyMutationToken",["Base64","PrivacyMutationSourceIDContext","react","react-compiler-runtime"],(function(a,b,c,d,e,f,g){"use strict";var h;b=h||d("react");var i=b.useContext;b.useMemo;function a(){var a=d("react-compiler-runtime").c(2),b=i(c("PrivacyMutationSourceIDContext")),e;a[0]!==b?(e=j(b),a[0]=b,a[1]=e):e=a[1];b=e;return b}function j(a){return a==null?null:c("Base64").encode(JSON.stringify({callsite_id:a,creation_time:Date.now(),type:0}))}g.usePrivacyMutationToken=a;g.getPrivacyMutationTokenFromSourceID=j}),98);
__d("UnifiedShareSheetDialogContext",["react"],(function(a,b,c,d,e,f,g){"use strict";var h;a=h||d("react");b={isShareSheetEntrypoint:!1,setShouldHideMessengerSection:function(a){},setShouldHideShareToSection:function(a){}};c=a.createContext(b);g["default"]=c}),98);
__d("composerLexicalMessageFeedTransformDeferred",["getDeferredComposerTransformer","requireDeferred"],(function(a,b,c,d,e,f,g){"use strict";a=c("getDeferredComposerTransformer")(c("requireDeferred")("composerLexicalMessageFeedTransform").__setRef("composerLexicalMessageFeedTransformDeferred"));g["default"]=a}),98);
__d("getFeedComposerLoggingPayloadForDraftJS",["getComposerLoggingPayload"],(function(a,b,c,d,e,f,g){"use strict";function a(a){var b,c;return{character:(a==null?void 0:a.editorState)!=null?d("getComposerLoggingPayload").getCharacterLength(a==null?void 0:a.editorState):0,location_tag:(a==null||(b=a.locationMinutiae)==null?void 0:b.placeID)!=null?1:0,photo:(a==null?void 0:a.mediaAttachments)!=null?d("getComposerLoggingPayload").getPhotoCount(a==null?void 0:a.mediaAttachments):0,qplEvent:a!=null?d("getComposerLoggingPayload").getQPLEvent(a):null,shared_link:(a==null||(c=a.linkAttachment)==null?void 0:c.url)!=null?1:0,text_background:0,video:(a==null?void 0:a.mediaAttachments)!=null?d("getComposerLoggingPayload").getVideoCount(a==null?void 0:a.mediaAttachments):0}}g["default"]=a}),98);
__d("getFeedComposerLoggingPayloadForLexical",["LexicalText","cr:8483","getComposerLoggingPayload"],(function(a,b,c,d,e,f,g){"use strict";function a(a){var c,e;return babelHelpers["extends"]({character:a.lexicalEditor!=null?a.lexicalEditor.getEditorState().read(d("LexicalText").$rootTextContent).length:0,location_tag:(a==null||(c=a.locationMinutiae)==null?void 0:c.placeID)!=null?1:0,photo:(a==null?void 0:a.mediaAttachments)!=null?d("getComposerLoggingPayload").getPhotoCount(a==null?void 0:a.mediaAttachments):0,qplEvent:a!=null?d("getComposerLoggingPayload").getQPLEvent(a):null},b("cr:8483")!=null?b("cr:8483")(a==null?void 0:a.editorState):null,{shared_link:(a==null||(e=a.linkAttachment)==null?void 0:e.url)!=null?1:0,text_background:0,video:(a==null?void 0:a.mediaAttachments)!=null?d("getComposerLoggingPayload").getVideoCount(a==null?void 0:a.mediaAttachments):0})}g["default"]=a}),98);
__d("getComposerLoggingPayload",["UnicodeUtils","getFeedComposerLoggingPayloadForDraftJS","getFeedComposerLoggingPayloadForLexical","getPlainTextFromDeferredDraftEditorState_DEPRECATED_DO_NOT_USE","qpl"],(function(a,b,c,d,e,f,g){"use strict";var h;function a(a){if(a.__CAN_USE_LEXICAL_RUNTIME_CHECK__===!0&&a.lexicalEditor!=null)return c("getFeedComposerLoggingPayloadForLexical")(a);else return c("getFeedComposerLoggingPayloadForDraftJS")(a)}function b(a){var b,c,d;return{character:(b=a==null||(c=a.satpData)==null||(c=c.text)==null?void 0:c.length)!=null?b:0,location_tag:0,photo:(a==null?void 0:a.mediaAttachments)!=null?i(a==null?void 0:a.mediaAttachments):0,qplEvent:null,shared_link:0,text_background:(a==null||(d=a.satpData)==null?void 0:d.fontID)==null?0:1,video:(a==null?void 0:a.mediaAttachments)!=null?j(a==null?void 0:a.mediaAttachments):0}}function e(a){a=c("getPlainTextFromDeferredDraftEditorState_DEPRECATED_DO_NOT_USE")(a);return(h||(h=d("UnicodeUtils"))).strlen(a)}function i(a){return a==null?0:a.filter(function(a){return a.fileType==="PHOTO"}).length}function j(a){return a==null?0:a.filter(function(a){return a.fileType==="VIDEO"}).length}function f(a){return a.photo3dAttachment!=null?c("qpl")._(37631558,"4977"):null}g.getFeedComposerLoggingPayload=a;g.getStoriesComposerLoggingPayload=b;g.getCharacterLength=e;g.getPhotoCount=i;g.getVideoCount=j;g.getQPLEvent=f}),98);
__d("getTextLengthLimitReachedText",["fbt"],(function(a,b,c,d,e,f,g,h){"use strict";function a(a){var b=a.limit;a=a.numCharacters;return h._(/*BTDS*/"_j{\"*\":{\"*\":\"A status can\\u2019t be longer than {maxselect} characters. Please make yours {number} characters shorter and try again.\"}}",[h._param("maxselect",b,[0]),h._param("number",a-b,[0])])}g["default"]=a}),226);
__d("useCometComposerPrivacyPushPage",["CometComposerPushPageContext","react","react-compiler-runtime"],(function(a,b,c,d,e,f,g){"use strict";var h,i=h||(h=d("react"));b=h;var j=b.useContext;b.useMemo;function a(a){var b=d("react-compiler-runtime").c(6),e=a.onClose,f=a.styles,g=a.withBackButton,h=a.withCloseButton,m=(a=j(c("CometComposerPushPageContext")))==null?void 0:a.pushPageHandler;bb0:{if(m==null){a=void 0;break bb0}var n;b[0]!==m||b[1]!==e||b[2]!==f||b[3]!==g||b[4]!==h?(n=function(a,b){m(String(b==null?void 0:b.title),function(b){b=b.onReturn;return i.jsx("div",{className:f,children:i.jsx(a,{onReturn:b,setTitle:l})})},!1,{onBack:function(){var a=b==null?void 0:b.onBack;a&&a(k)},onClose:e,withBackButton:g,withCloseButton:h})},b[0]=m,b[1]=e,b[2]=f,b[3]=g,b[4]=h,b[5]=n):n=b[5];a=n}return a}function k(){}function l(){}g["default"]=a}),98);
__d("useLexicalIsTextContentEmpty",["cr:1022"],(function(a,b,c,d,e,f){e.exports=b("cr:1022")}),null);
/**
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 *
 *
 * @fullSyntaxTransform
 * @es6-async_DO_NOT_USE
 * @generated SignedSource<<16f22a53fef6760f4bf37e7f7c631e39>>
 * 
 * @nolint
 * @oncall lexical_web_text_editor
 * @preserve-invariant-messages
 * @preserve-whitespace
 * @preventMunge
 */__d("useLexicalIsTextContentEmpty.prod",["LexicalText","react"],(function $module_useLexicalIsTextContentEmpty_prod(global,require,requireDynamic,requireLazy,module,exports){

"use strict";var _require_closure_react;var t=_require_closure_react||(_require_closure_react=require("react"));var o="undefined"!=typeof window&&void 0!==window.document&&void 0!==window.document.createElement?t.useLayoutEffect:t.useEffect;exports.useLexicalIsTextContentEmpty=function(n,i){var _t$useState=t.useState(n.getEditorState().read(require("LexicalText").$isRootTextContentEmptyCurry(n.isComposing(),i))),r=_t$useState[0],s=_t$useState[1];return o(function(){return n.registerUpdateListener(function(_ref){var t=_ref.editorState;var o=n.isComposing(),r=t.read(require("LexicalText").$isRootTextContentEmptyCurry(o,i));s(r);});},[n,i]),r;};}),null);