;/*FB_PKG_DELIM*/

__d("BaseMultiPageEntryPointImpl.react",["CometPlaceholder.react","CometRelay","clearTimeout","react","react-compiler-runtime","setTimeout"],(function(a,b,c,d,e,f,g){"use strict";var h,i=h||(h=d("react"));b=h;var j=b.useEffect,k=b.useRef;function a(a){var b=d("react-compiler-runtime").c(15),e=a.entryPoint,f=a.environmentProvider,g=a.fallback,h=a.loadedEntryPoint,l=a.otherProps,m=a.placeholderComponent,n=a.preloadParams;a=a.usePlaceholder;m=m===void 0?c("CometPlaceholder.react"):m;a=a===void 0?!0:a;f=d("CometRelay").useEntryPointLoader(f,e);var o=f[0],p=f[1],q=f[2],r=o!=null?o:h,s=k(null);b[0]!==q||b[1]!==r.isDisposed||b[2]!==h||b[3]!==n||b[4]!==p||b[5]!==o?(e=function(){s.current!=null&&(c("clearTimeout")(s.current),s.current=null);r.isDisposed&&p(n);return function(){s.current=c("setTimeout")(function(){o?q():h.dispose(),s.current=null},6e4)}},f=[q,r.isDisposed,h,n,p,o],b[0]=q,b[1]=r.isDisposed,b[2]=h,b[3]=n,b[4]=p,b[5]=o,b[6]=e,b[7]=f):(e=b[6],f=b[7]);j(e,f);b[8]!==r||b[9]!==l?(e=i.jsx(d("CometRelay").EntryPointContainer,{entryPointReference:r,props:l}),b[8]=r,b[9]=l,b[10]=e):e=b[10];f=e;if(!a)return f;b[11]!==m||b[12]!==f||b[13]!==g?(l=i.jsx(m,{fallback:g,children:f}),b[11]=m,b[12]=f,b[13]=g,b[14]=l):l=b[14];return l}g["default"]=a}),98);
__d("FDSCheckmarkFilled20Icon",["cr:14115"],(function(a,b,c,d,e,f,g){"use strict";g["default"]=b("cr:14115")}),98);
__d("FDSCheckmarkFilled20PNGIcon.react",["ix","fbicon"],(function(a,b,c,d,e,f,g,h){"use strict";a=d("fbicon")._(h("477814"),20);b=a;g["default"]=b}),98);
__d("LSFetchBanners",["LSIssueNewTask"],(function(a,b,c,d,e,f){function a(){var a=arguments,c=a[a.length-1],d=[],e=[];return c.sequence([function(e){return d[0]=new c.Map(),d[0].set("thread_key",a[0]),d[1]=c.toJSON(d[0]),c.storedProcedure(b("LSIssueNewTask"),"in_thread_banner_fetch_activity_banners_queue",c.i64.cast([0,72]),d[1],void 0,void 0,c.i64.cast([0,0]),c.i64.cast([0,0]),void 0,void 0,c.i64.cast([0,0]),c.i64.cast([0,0]))},function(a){return c.resolve(e)}])}a.__sproc_name__="LSInThreadBannerFetchBannersStoredProcedure";a.__tables__=[];e.exports=a}),null);
__d("MWInChatTabContextProvider.react",["react","react-compiler-runtime"],(function(a,b,c,d,e,f,g){"use strict";var h,i=h||(h=d("react"));c=h;e=c.createContext;var j=c.useContext,k=e(!1);function a(){return j(k)}function b(a){var b=d("react-compiler-runtime").c(2);a=a.children;var c;b[0]!==a?(c=i.jsx(k.Provider,{value:!0,children:a}),b[0]=a,b[1]=c):c=b[1];return c}g.useInChatTab=a;g.InChatTabContextProvider=b}),98);
__d("ProfilePlusSwitchProfilesUnifiedShareSheetShareToPageQuery_facebookRelayOperation",[],(function(a,b,c,d,e,f){e.exports="23949440778006947"}),null);
__d("VideoPlayerHTML5ApiWebVttState",["Bootloader","unrecoverableViolation"],(function(a,b,c,d,e,f,g){"use strict";a=function(){function a(a){var b=this,d=a.onReady,e=a.onCaptionsLoaded,f=a.captionsDisplay;this.$1=null;this.source=null;this.captionsDisplay=null;this.$1=c("Bootloader").loadModules(["VideoPlayerWebVttCaptionsSource"],function(a){a=new a({onCaptionsLoaded:e,onCaptionsChanged:function(a,c){b.captionsDisplay&&b.captionsDisplay.handleCaptionsChanged(a,c)}});b.source=a;b.captionsDisplay=f;d(b)},"VideoPlayerHTML5ApiWebVttState")}var b=a.prototype;b.loadFromUrl=function(a){var b=this.source;if(!b)throw c("unrecoverableViolation")("[VideoPlayerHTML5ApiWebVttState] Called loadFromUrl when not ready; call from onReady callback.","video_captions");b.loadFromUrl(a)};b.getCurrentScreenRepresentation=function(){return this.source?this.source.getCurrentScreenRepresentation():null};b.destroy=function(){this.$1&&(this.$1.remove(),this.$1=null),this.captionsDisplay&&(this.captionsDisplay.destroy(),this.captionsDisplay=null),this.source&&(this.source.destroy(),this.source=null)};return a}();g["default"]=a}),98);
__d("WebBloksSSRUtils",[],(function(a,b,c,d,e,f){a=!!(typeof window!=="undefined"&&window.document&&window.document.createElement);f.canUseDOM=a}),66);
__d("usePageEntryPointPrerenderer",["FBLogger","react","react-compiler-runtime","useCometEntryPointPrerendererWithQueryTimeoutPrivate"],(function(a,b,c,d,e,f,g){"use strict";var h;b=h||d("react");b.useCallback;var i=b.useState;function a(a,b,e){var f=d("react-compiler-runtime").c(6),g=i(),h=g[0],j=g[1];g=c("useCometEntryPointPrerendererWithQueryTimeoutPrivate")(a,b,e);var k=g[0];a=g[1];f[0]!==k?(b=function(a){var b=k();j(b);if(b==null){c("FBLogger")("comet_ui").blameToPreviousFrame().mustfix("Unable to present comet page EntryPoint component, preloadParams not set");return}b!=null&&a(b)},f[0]=k,f[1]=b):b=f[1];e=b;f[2]!==e||f[3]!==a||f[4]!==h?(g=[e,a,h],f[2]=e,f[3]=a,f[4]=h,f[5]=g):g=f[5];return g}g["default"]=a}),98);
__d("usePushPage",["BaseMultiPageEntryPointImpl.react","BaseMultiPageViewContext","FBLogger","react","react-compiler-runtime","useCometRelayEntrypointContextualEnvironmentProvider","usePageEntryPointPrerenderer"],(function(a,b,c,d,e,f,g){"use strict";var h,i=h||(h=d("react"));b=h;b.useCallback;var j=b.useContext;function a(a,b,e){var f=d("react-compiler-runtime").c(9);e=e===void 0?"button":e;var g=c("useCometRelayEntrypointContextualEnvironmentProvider")(),h=j(c("BaseMultiPageViewContext"));e=c("usePageEntryPointPrerenderer")(a,b,e);var k=e[0];e=e[1];var l;f[0]!==h||f[1]!==g||f[2]!==k||f[3]!==a||f[4]!==b?(l=function(e,d){d=d===void 0?{}:d;var f=d.fallback,j=d.pageKey;if(h==null)throw c("FBLogger")("BaseMultiPageView").blameToPreviousFrame().mustfixThrow("usePushPage can only be used inside BaseMultiPageView.");if(b==null)return;k(function(d){return h.pushPage(function(){return i.jsx(c("BaseMultiPageEntryPointImpl.react"),{entryPoint:a,environmentProvider:g,fallback:f!=null?f:h.fallback,loadedEntryPoint:d,otherProps:e,placeholderComponent:h.placeholderComponent,preloadParams:b})},{pageKey:j})})},f[0]=h,f[1]=g,f[2]=k,f[3]=a,f[4]=b,f[5]=l):l=f[5];l=l;var m;f[6]!==e||f[7]!==l?(m=[l,e],f[6]=e,f[7]=l,f[8]=m):m=f[8];return m}g["default"]=a}),98);