import { CARD_TYPE, ICard } from "../models/cards.models";

const actions: ICard[] = [
  {
    name: "Peek",
    qty: 3,
    cost: {
      apples: 0,
      carrots: 0,
      berries: 0,
      any: 1,
    },
    image: "rummager",
    description: "Look at the top card of a shop deck.",
    type: CARD_TYPE.Action,
  },
  {
    name: "Exchange",
    qty: 3,
    cost: {
      apples: 0,
      carrots: 0,
      berries: 0,
      any: 1,
    },
    image: "rummager",
    description: "Gain any 1 crop.",
    type: CARD_TYPE.Action,
  },
  {
    name: "Overtime",
    qty: 3,
    cost: {
      apples: 0,
      carrots: 0,
      berries: 0,
      any: 1,
    },
    image: "rummager",
    description: "Pack a crop from your stash into your work order",
    type: CARD_TYPE.Action,
  },
  {
    name: "Tick it off",
    qty: 3,
    cost: {
      apples: 0,
      carrots: 0,
      berries: 0,
      any: 1,
    },
    image: "rummager",
    description: "Progress your task by 1.",
    type: CARD_TYPE.Action,
  },
  {
    name: "Pester",
    qty: 3,
    cost: {
      apples: 0,
      carrots: 0,
      berries: 0,
      any: 1,
    },
    image: "rummager",
    description: "-1 Energy from any critter.",
    type: CARD_TYPE.Action,
  },
  {
    name: "Try again",
    qty: 3,
    cost: {
      apples: 0,
      carrots: 0,
      berries: 0,
      any: 1,
    },
    image: "rummager",
    description: "Discard a card to draw a card.",
    type: CARD_TYPE.Action,
  },
  {
    name: "Cheat",
    qty: 2,
    cost: {
      apples: 0,
      carrots: 0,
      berries: 0,
      any: 2,
    },
    image: "rummager",
    description: "Shuffle a card from your discard pile into your deck.",
    type: CARD_TYPE.Action,
  },
  {
    name: "Collect",
    qty: 2,
    cost: {
      apples: 0,
      carrots: 0,
      berries: 0,
      any: 2,
    },
    image: "rummager",
    description: "Draw a card.",
    type: CARD_TYPE.Action,
  },
  {
    name: "Refresh",
    qty: 2,
    cost: {
      apples: 0,
      carrots: 0,
      berries: 0,
      any: 2,
    },
    image: "rummager",
    description: "Refresh a card in the shop.",
    type: CARD_TYPE.Action,
  },
  {
    name: "Reserve",
    qty: 2,
    cost: {
      apples: 0,
      carrots: 0,
      berries: 0,
      any: 2,
    },
    image: "rummager",
    description:
      "Reserve a card in the shop, only you may buy it. (Refreshing removes this)",
    type: CARD_TYPE.Action,
  },
  {
    name: "Refund",
    qty: 2,
    cost: {
      apples: 0,
      carrots: 0,
      berries: 0,
      any: 2,
    },
    image: "rummager",
    description: "Refund a card from your hand.",
    type: CARD_TYPE.Action,
  },
  {
    name: "Forecast",
    qty: 2,
    cost: {
      apples: 0,
      carrots: 0,
      berries: 0,
      any: 2,
    },
    image: "rummager",
    description: "Look at the top 3 cards of your deck.",
    type: CARD_TYPE.Action,
  },
];

export default actions;
