import { CARD_SUBTYPE, CARD_TYPE, ICard, TAGS } from "../models/cards.models";

const items: ICard[] = [
  {
    name: "Recycling Bin",
    cost: {
      apples: 0,
      berries: 3,
      carrots: 1,
    },
    qty: 1,
    type: CARD_TYPE.Item,
    subtype: CARD_SUBTYPE.FINANCE,
    tags: [TAGS.CROP_GENERATION_APPLE, TAGS.SHUFFLE_CARDS, TAGS.HOLDABLE],
    description: "Gain +2 Apples. Fast-track an Item card. Holdable.",
    buyBonus: "Discount",
  },
  {
    name: "Closed Sign",
    cost: {
      apples: 3,
      berries: 1,
      carrots: 0,
    },
    qty: 1,
    type: CARD_TYPE.Item,
    subtype: CARD_SUBTYPE.FINANCE,
    tags: [TAGS.CROP_GENERATION_CARROT, TAGS.TRASH],
    description: "Gain +2 Carrots. Add 1 Zzz to EVERY critter.",
    buyBonus: "Discount",
  },
  {
    name: "Loyalty Card",
    cost: {
      apples: 1,
      berries: 0,
      carrots: 3,
    },
    qty: 1,
    type: CARD_TYPE.Item,
    subtype: CARD_SUBTYPE.FINANCE,
    tags: [TAGS.CROP_GENERATION_BERRY, TAGS.DISCOUNT, TAGS.SHUFFLE_CARDS],
    description:
      "Gain +2 Berries. Snatch a discounted crop from a card in the Market.",
    buyBonus: "Discount",
  },
  {
    name: "Cooked Books",
    cost: {
      apples: 1,
      berries: 3,
      carrots: 1,
    },
    qty: 1,
    type: CARD_TYPE.Item,
    subtype: CARD_SUBTYPE.FINANCE,
    tags: [
      TAGS.REFUND,
      TAGS.REFUND_FROM_DISCARD,
      TAGS.REFUND_FROM_HAND,
      TAGS.FINANCE_SYNERGY,
      TAGS.TOP_OF_DECK,
    ],
    description:
      "Sell a card from your discard pile. If it is a Finance card, put it back on top of your deck after.",
  },
  {
    name: "Instruction manual",
    cost: {
      apples: 1,
      berries: 2,
      carrots: 3,
    },
    qty: 1,
    type: CARD_TYPE.Item,
    subtype: CARD_SUBTYPE.FINANCE,
    tags: [TAGS.DISCARD_OWN, TAGS.PACK_CRATE],
    description:
      "Discard a card from hand to pack a free crate into a Work Order.",
    onDiscard: "Draw 2 cards.",
  },
  {
    name: "Damaged Goods",
    cost: {
      apples: 3,
      berries: 1,
      carrots: 1,
    },
    qty: 1,
    type: CARD_TYPE.Item,
    subtype: CARD_SUBTYPE.FINANCE,
    tags: [TAGS.REFUND, TAGS.REFUND_FROM_DISCARD, TAGS.TRASH, TAGS.HOLDABLE],
    description:
      "Sell a card from your discard pile -OR- Trash 2 cards from your discard pile. Holdable.",
    onDiscard: "Gain 1 of each crop",
  },
  {
    name: "Gift Card",
    cost: {
      apples: 2,
      berries: 2,
      carrots: 2,
    },
    qty: 1,
    type: CARD_TYPE.Item,
    subtype: CARD_SUBTYPE.FINANCE,
    tags: [TAGS.TOP_OF_DECK, TAGS.FREE_CARD],
    description:
      "Put a Farm card from the shop on top of your deck. Put Gift Card back into the shop.",
  },
  {
    name: "Paper Shredder",
    cost: {
      apples: 0,
      berries: 2,
      carrots: 3,
    },
    qty: 1,
    type: CARD_TYPE.Item,
    subtype: CARD_SUBTYPE.FINANCE,
    tags: [TAGS.DISCOUNT, TAGS.ENERGY_REMOVE],
    description: "Play an Item card from your discard pile, and then Trash it.",
    buyBonus: "Fast-track a card.",
  },
  {
    name: "Open Sign",
    cost: {
      apples: 3,
      berries: 0,
      carrots: 1,
    },
    qty: 1,
    type: CARD_TYPE.Item,
    subtype: CARD_SUBTYPE.FINANCE,
    tags: [TAGS.REFRESH_SHOP, TAGS.DISCOUNT, TAGS.CROP_GENERATION_RANDOM],
    description:
      "Refresh 2 cards in the Market. Gain 2 random crops. Discount.",
    buyBonus: "Put this card into your hand.",
  },
  {
    name: "Contrabrand",
    cost: {
      apples: 2,
      berries: 3,
      carrots: 0,
    },
    qty: 1,
    type: CARD_TYPE.Item,
    subtype: CARD_SUBTYPE.FINANCE,
    tags: [TAGS.GIFT, TAGS.TRASH],
    description: "Gift a card from your discard pile. Unsellable.",
    onDiscard: "Trash this card",
  },
  {
    name: "Register",
    cost: {
      apples: 2,
      berries: 1,
      carrots: 2,
    },
    qty: 1,
    type: CARD_TYPE.Item,
    subtype: CARD_SUBTYPE.FINANCE,
    tags: [TAGS.CROP_STEAL, TAGS.CROP_GENERATION_RANDOM],
    description:
      "Steal one type of crop from a Rival until your have more of that crop than they do.",
    onDiscard: "Gain 3 random crops.",
  },
  {
    name: "Receipts",
    cost: {
      apples: 1,
      berries: 1,
      carrots: 2,
    },
    qty: 1,
    type: CARD_TYPE.Item,
    subtype: CARD_SUBTYPE.FINANCE,
    tags: [TAGS.REFUND, TAGS.REFUND_FROM_HAND, TAGS.CANTRIP, TAGS.DISCOUNT],
    description: "Sell a card from your hand. Draw a card. Discount.",
    onDiscard: "Gain +2 of a random crop.",
  },
  {
    name: "Farming Gloves",
    cost: {
      apples: 0,
      berries: 2,
      carrots: 2,
    },
    qty: 1,
    type: CARD_TYPE.Item,
    subtype: CARD_SUBTYPE.TOOL,
    tags: [TAGS.CROP_GENERATION_APPLE, TAGS.SEED_SYNERGY, TAGS.SUNLIGHT_ADD],
    description: "Gain +2 Apples. Add 1 Sunlight to each of your Seeds.",
    buyBonus: "Fast-track a Seed card.",
  },
  {
    name: "Binoculars",
    cost: {
      apples: 2,
      berries: 2,
      carrots: 0,
    },
    qty: 1,
    type: CARD_TYPE.Item,
    subtype: CARD_SUBTYPE.TOOL,
    tags: [TAGS.CROP_GENERATION_CARROT, TAGS.TOP_OF_DECK, TAGS.DISCARD_OWN],
    description: "Gain +2 Carrots. Fast-track a Critter card.",
    buyBonus: "Refresh a card.",
  },
  {
    name: "Water Cooler",
    cost: {
      apples: 2,
      berries: 0,
      carrots: 2,
    },
    qty: 1,
    type: CARD_TYPE.Item,
    subtype: CARD_SUBTYPE.TOOL,
    tags: [],
    description:
      "Gain +2 Berries. Move 1 Zzz from one of your Critters to ANY other Critter.",
    buyBonus: "Add 1 Zzz to a Critter",
  },
  {
    name: "Small Backpack",
    cost: {
      apples: 3,
      berries: 0,
      carrots: 3,
    },
    qty: 1,
    type: CARD_TYPE.Item,
    subtype: CARD_SUBTYPE.TOOL,
    tags: [TAGS.DISCARD_OWN, TAGS.CARD_DRAW, TAGS.TRASH],
    description: "Discard a card from hand to draw 2 cards.",
    buyBonus: "Trash a card from your discard pile.",
  },
  {
    name: "Convincing Disguise",
    cost: {
      apples: 0,
      berries: 2,
      carrots: 1,
    },
    qty: 1,
    type: CARD_TYPE.Item,
    subtype: CARD_SUBTYPE.TOOL,
    tags: [TAGS.CROP_GENERATION_RANDOM, TAGS.DISCARD_RIVAL_DECK],
    description:
      "Gain +2 of a random crop. Discard one of the top 3 cards of a ANY deck.",
    onDiscard: "Steal 2 crops from a Rival",
  },
  {
    name: "Watering Can",
    cost: {
      apples: 0,
      berries: 2,
      carrots: 2,
    },
    qty: 1,
    type: CARD_TYPE.Item,
    subtype: CARD_SUBTYPE.TOOL,
    tags: [TAGS.TOP_OF_DECK],
    description: "Put a card from your discard pile on top of your deck.",
    buyBonus: "Put this card on top of your deck.",
  },
  {
    name: "Dustpan",
    cost: {
      apples: 2,
      berries: 2,
      carrots: 2,
    },
    qty: 1,
    type: CARD_TYPE.Item,
    subtype: CARD_SUBTYPE.TOOL,
    tags: [TAGS.CANTRIP, TAGS.REFUND, TAGS.REFUND_FROM_HAND, TAGS.REFRESH_SHOP],
    description: "Refresh a row in the Market. Gain 1 of each crop. Discount.",
    onDiscard: "Reset your deck.",
  },
  {
    name: "Knapsack",
    cost: {
      apples: 3,
      berries: 0,
      carrots: 1,
    },
    qty: 1,
    type: CARD_TYPE.Item,
    subtype: CARD_SUBTYPE.TOOL,
    tags: [TAGS.DISCARD_OWN, TAGS.CROP_STEAL],
    description:
      "Steal 2 crops from a Rival. Discard a card from hand to steal 1 more.",
    onDiscard: "Gain 3 random crops",
  },
  {
    name: "Compost Bin",
    cost: {
      apples: 1,
      berries: 3,
      carrots: 3,
    },
    qty: 1,
    type: CARD_TYPE.Item,
    subtype: CARD_SUBTYPE.TOOL,
    tags: [TAGS.DISCARD_OWN, TAGS.CROP_GENERATION_RANDOM],
    description:
      "Discard every card from your hand. Gain 1 of each crop for each card discarded.",
    onDiscard: "Gain 1 of each crop.",
  },
  {
    name: "Toolbelt",
    cost: {
      apples: 1,
      berries: 3,
      carrots: 0,
    },
    qty: 1,
    type: CARD_TYPE.Item,
    subtype: CARD_SUBTYPE.TOOL,
    tags: [
      TAGS.SHUFFLE_CARDS,
      TAGS.TOOL_SYNERGY,
      TAGS.TOP_OF_DECK,
      TAGS.HOLDABLE,
    ],
    description:
      "Put a Tool from your discard pile on top of your deck. Holdable.",
    onDiscard: "Draw a card.",
  },
  {
    name: "Trusty Trowel",
    cost: {
      apples: 2,
      berries: 1,
      carrots: 2,
    },
    qty: 1,
    type: CARD_TYPE.Item,
    subtype: CARD_SUBTYPE.TOOL,
    tags: [TAGS.CROP_GENERATION_RANDOM, TAGS.SEED_SYNERGY, TAGS.CARD_DRAW],
    description:
      "Gain +3 of a random crop. Put a Seed card from your discard pile into your hand.",
  },
  {
    name: "Dusty Broom",
    cost: {
      apples: 2,
      berries: 1,
      carrots: 0,
    },
    qty: 1,
    type: CARD_TYPE.Item,
    subtype: CARD_SUBTYPE.TOOL,
    tags: [TAGS.DISCOUNT, TAGS.SNATCH_DISCOUNT, TAGS.REFRESH_SHOP],
    description:
      "Discount, Snatch the discounted crops from a card in the Market, then refresh that card.",
    buyBonus: "Reset your deck.",
  },
  {
    name: "Rat Food",
    cost: {
      apples: 3,
      berries: 1,
      carrots: 1,
    },
    qty: 1,
    type: CARD_TYPE.Item,
    subtype: CARD_SUBTYPE.TREAT,
    tags: [TAGS.CROP_GENERATION_APPLE, TAGS.REFRESH_SHOP],
    description: "Gain +3 Apples. Refresh 2 cards.",
  },
  {
    name: "Rabbit Food",
    cost: {
      apples: 1,
      berries: 1,
      carrots: 3,
    },
    qty: 1,
    type: CARD_TYPE.Item,
    subtype: CARD_SUBTYPE.TREAT,
    tags: [TAGS.CROP_GENERATION_CARROT, TAGS.ENERGY_RESTORE],
    description:
      "Gain +3 Carrots. Remove 1 Zzz counter from 3 of your Critters.",
  },
  {
    name: "Hog Food",
    cost: {
      apples: 1,
      berries: 3,
      carrots: 1,
    },
    qty: 1,
    type: CARD_TYPE.Item,
    subtype: CARD_SUBTYPE.TREAT,
    tags: [TAGS.CROP_GENERATION_BERRY, TAGS.TREAT_SYNERGY, TAGS.SHUFFLE_CARDS],
    description: "Gain +3 Berries. Fast-track this or another Treat.",
  },
  {
    name: "Picnic Basket",
    cost: {
      apples: 2,
      berries: 3,
      carrots: 2,
    },
    qty: 1,
    type: CARD_TYPE.Item,
    subtype: CARD_SUBTYPE.TREAT,
    tags: [TAGS.CROP_GENERATION_ALL],
    description: "Gain +2 of a random crop. Gain +1 of each other crop.",
    onDiscard: "Gain +2 of each crop.",
  },
  {
    name: "Award Winning Crop",
    cost: {
      apples: 3,
      berries: 2,
      carrots: 2,
    },
    qty: 1,
    type: CARD_TYPE.Item,
    subtype: CARD_SUBTYPE.TREAT,
    tags: [TAGS.CROP_GENERATION_RANDOM],
    description: "Gain +5 of a random crop.",
    onDiscard: "Draw 2 cards.",
  },
  {
    name: "Gift Basket",
    cost: {
      apples: 4,
      berries: 4,
      carrots: 4,
    },
    qty: 1,
    type: CARD_TYPE.Item,
    subtype: CARD_SUBTYPE.TREAT,
    tags: [TAGS.CROP_GENERATION_ALL],
    description: "Gain +2 of each crop.",
    buyBonus: "Each Rival gets +1 of each crop.",
  },
  {
    name: "Pot of Feed",
    cost: {
      apples: 3,
      berries: 3,
      carrots: 3,
    },
    qty: 1,
    type: CARD_TYPE.Item,
    subtype: CARD_SUBTYPE.TREAT,
    tags: [TAGS.ENERGY_RESTORE, TAGS.CARD_DRAW],
    description: "Draw 2 cards",
    buyBonus: "Remove 1 Zzz counter from each of your Critters.",
  },
  {
    name: "Midnight Snack",
    cost: {
      apples: 2,
      berries: 1,
      carrots: 1,
    },
    qty: 1,
    type: CARD_TYPE.Item,
    subtype: CARD_SUBTYPE.TREAT,
    tags: [TAGS.CROP_GENERATION_RANDOM, TAGS.CANTRIP],
    description: "Gain a random crop. Draw a card.",
    buyBonus: "Each player gets a random crop",
  },
  {
    name: "Pik'n'mix",
    cost: {
      apples: 0,
      berries: 3,
      carrots: 3,
    },
    qty: 1,
    type: CARD_TYPE.Item,
    subtype: CARD_SUBTYPE.TREAT,
    tags: [TAGS.CROP_GENERATION, TAGS.CROP_GENERATION_RANDOM],
    description: "Gain 3 random crops, then gain a crop of your choosing.",
  },
  {
    name: "Morning Cuppa'",
    cost: {
      apples: 1,
      berries: 2,
      carrots: 0,
    },
    qty: 1,
    type: CARD_TYPE.Item,
    subtype: CARD_SUBTYPE.TREAT,
    tags: [TAGS.ENERGY_RESTORE, TAGS.HOLDABLE],
    description: "Remove all Zzz counters from one of your Critters. Holdable",
    onDiscard: "Exhaust a Rival's Critter.",
  },
  {
    name: "Sharing Plate",
    cost: {
      apples: 2,
      berries: 2,
      carrots: 2,
    },
    qty: 1,
    type: CARD_TYPE.Item,
    subtype: CARD_SUBTYPE.TREAT,
    tags: [TAGS.CROP_GENERATION_RANDOM],
    description:
      "Gain +4 of a crop of your choosing. Each Rival also gains +1 of that crop.",
  },
  {
    name: "Plant Food",
    cost: {
      apples: 3,
      berries: 0,
      carrots: 3,
    },
    qty: 1,
    type: CARD_TYPE.Item,
    subtype: CARD_SUBTYPE.TREAT,
    tags: [TAGS.SEED_SYNERGY],
    description:
      "Harvest a Seed card from your discard pile as though it had 3 Sunlight. Holdable.",
  },
  {
    name: "Goldfish",
    cost: {
      apples: 2,
      berries: 2,
      carrots: 2,
    },
    qty: 1,
    type: CARD_TYPE.Item,
    subtype: CARD_SUBTYPE.GIFT,
    tags: [TAGS.GIFT],
    description: "This does nothing. You cannot Sell or Trash this card..",
    buyBonus: "Gift this to a Rival.",
  },
  {
    name: "Birthday Present",
    cost: {
      apples: 0,
      berries: 0,
      carrots: 2,
    },
    qty: 1,
    type: CARD_TYPE.Item,
    subtype: CARD_SUBTYPE.GIFT,
    tags: [TAGS.GIFT, TAGS.CROP_GENERATION_RANDOM],
    description: "Gain 3 random crops, then gift this to a Rival.",
  },
  {
    name: "Hot Potato",
    cost: {
      apples: 2,
      berries: 0,
      carrots: 0,
    },
    qty: 1,
    type: CARD_TYPE.Item,
    subtype: CARD_SUBTYPE.GIFT,
    tags: [TAGS.GIFT, TAGS.CROP_DESTROY],
    description: "Destroy 2 of your crops to Gift this to a Rival. Unsellable.",
    buyBonus: "Gift this to a Rival.",
  },
  {
    name: "Rotten Crops",
    cost: {
      apples: 0,
      berries: 2,
      carrots: 0,
    },
    qty: 1,
    type: CARD_TYPE.Item,
    subtype: CARD_SUBTYPE.GIFT,
    tags: [TAGS.GIFT, TAGS.CROP_DESTROY],
    description: "Destroy 2 of your crops to draw a card. Unsellable.",
    buyBonus: "Gift this to a Rival",
  },
];

export default items;
