import { CARD_SUBTYPE, CARD_TYPE, ICard, TAGS } from "../models/cards.models";

const items: ICard[] = [
  {
    name: "Recycling Bin",
    cost: {
      apples: 0,
      berries: 3,
      carrots: 1,
    },
    qty: 1,
    type: CARD_TYPE.Item,
    subtype: CARD_SUBTYPE.FINANCE,
    tags: [TAGS.CROP_GENERATION_APPLE, TAGS.SHUFFLE_CARDS, TAGS.HOLDABLE],
    description:
      "Gain +2 Apples. Shuffle a card from your discard pile into your deck. Holdable.",
  },
  {
    name: "Paper Shredder",
    cost: {
      apples: 3,
      berries: 1,
      carrots: 0,
    },
    qty: 1,
    type: CARD_TYPE.Item,
    subtype: CARD_SUBTYPE.FINANCE,
    tags: [TAGS.CROP_GENERATION_CARROT, TAGS.TRASH],
    description: "Gain +2 Carrots. Trash a card from your discard pile.",
  },
  {
    name: "Loyalty Card",
    cost: {
      apples: 1,
      berries: 0,
      carrots: 3,
    },
    qty: 1,
    type: CARD_TYPE.Item,
    subtype: CARD_SUBTYPE.FINANCE,
    tags: [TAGS.CROP_GENERATION_BERRY, TAGS.DISCOUNT, TAGS.SHUFFLE_CARDS],
    description:
      "Gain +2 Berries. Discount once. The next farm card you buy this turn is shuffled into your deck.",
  },
  {
    name: "Cooked Books",
    cost: {
      apples: 1,
      berries: 3,
      carrots: 1,
    },
    qty: 1,
    type: CARD_TYPE.Item,
    subtype: CARD_SUBTYPE.FINANCE,
    tags: [
      TAGS.REFUND,
      TAGS.REFUND_FROM_DISCARD,
      TAGS.REFUND_FROM_HAND,
      TAGS.FINANCE_SYNERGY,
      TAGS.TOP_OF_DECK,
    ],
    description:
      "Refund a card from your hand or discard pile. If it is a Finance card, put it back on top of your deck.",
  },
  {
    name: "Instruction manual",
    cost: {
      apples: 1,
      berries: 2,
      carrots: 3,
    },
    qty: 1,
    type: CARD_TYPE.Item,
    subtype: CARD_SUBTYPE.FINANCE,
    tags: [TAGS.DISCARD_OWN, TAGS.PACK_CRATE],
    description:
      "Discard a card from hand to pack a free crate into a Work Order.",
    buyBonus: "Get a free Work Order.",
    onDiscard: "Draw 2 cards.",
  },
  {
    name: "Damaged Goods",
    cost: {
      apples: 3,
      berries: 1,
      carrots: 1,
    },
    qty: 1,
    type: CARD_TYPE.Item,
    subtype: CARD_SUBTYPE.FINANCE,
    tags: [TAGS.REFUND, TAGS.REFUND_FROM_DISCARD, TAGS.TRASH, TAGS.HOLDABLE],
    description:
      "Refund a card from your discard pile, or Trash 2 cards from your discard pile. Holdable.",
  },
  {
    name: "Gift Card",
    cost: {
      apples: 2,
      berries: 2,
      carrots: 2,
    },
    qty: 1,
    type: CARD_TYPE.Item,
    subtype: CARD_SUBTYPE.FINANCE,
    tags: [TAGS.TOP_OF_DECK, TAGS.FREE_CARD],
    description:
      "Put a Farm card from the shop on top of your deck. Put Gift Card back into the shop.",
  },
  {
    name: "Closed Sign",
    cost: {
      apples: 0,
      berries: 2,
      carrots: 3,
    },
    qty: 1,
    type: CARD_TYPE.Item,
    subtype: CARD_SUBTYPE.FINANCE,
    tags: [TAGS.DISCOUNT, TAGS.ENERGY_REMOVE],
    description:
      "Discount twice. Add a Zzz counter to EVERY critter. Gain 2 random crops for each Work Order you have.",
    buyBonus: "Discount once.",
  },
  {
    name: "Open Sign",
    cost: {
      apples: 3,
      berries: 0,
      carrots: 1,
    },
    qty: 1,
    type: CARD_TYPE.Item,
    subtype: CARD_SUBTYPE.FINANCE,
    tags: [TAGS.REFRESH_SHOP, TAGS.DISCOUNT, TAGS.CROP_GENERATION_RANDOM],
    description:
      "Refresh 2 cards in the shop. Discount once. Gain 2 random crops.",
  },
  {
    name: "Contrabrand",
    cost: {
      apples: 2,
      berries: 3,
      carrots: 0,
    },
    qty: 1,
    type: CARD_TYPE.Item,
    subtype: CARD_SUBTYPE.FINANCE,
    tags: [TAGS.GIFT, TAGS.TRASH],
    description:
      "Gift a Rival a card from your discard pile. Trash this card if this is still in your hand at the end of your turn.",
  },
  {
    name: "Register",
    cost: {
      apples: 2,
      berries: 1,
      carrots: 2,
    },
    qty: 1,
    type: CARD_TYPE.Item,
    subtype: CARD_SUBTYPE.FINANCE,
    tags: [TAGS.CROP_STEAL, TAGS.CROP_GENERATION_RANDOM],
    description:
      "Steal one type of crop from a Rival until your have more of that crop than they do.",
    onDiscard: "Gain 5 random crops.",
  },
  {
    name: "Receipts",
    cost: {
      apples: 1,
      berries: 1,
      carrots: 2,
    },
    qty: 1,
    type: CARD_TYPE.Item,
    subtype: CARD_SUBTYPE.FINANCE,
    tags: [TAGS.REFUND, TAGS.REFUND_FROM_HAND, TAGS.CANTRIP, TAGS.DISCOUNT],
    description: "Refund a card from your hand. Draw a card. Discount once.",
    buyBonus: "Discount once.",
  },
  {
    name: "Farming Gloves",
    cost: {
      apples: 0,
      berries: 2,
      carrots: 2,
    },
    qty: 1,
    type: CARD_TYPE.Item,
    subtype: CARD_SUBTYPE.TOOL,
    tags: [TAGS.CROP_GENERATION_APPLE, TAGS.SEED_SYNERGY, TAGS.SUNLIGHT_ADD],
    description: "Gain +2 Apples. Add 1 Sunlight to each of your Seeds.",
  },
  {
    name: "Binoculars",
    cost: {
      apples: 2,
      berries: 1,
      carrots: 0,
    },
    qty: 1,
    type: CARD_TYPE.Item,
    subtype: CARD_SUBTYPE.TOOL,
    tags: [TAGS.CROP_GENERATION_CARROT, TAGS.TOP_OF_DECK, TAGS.DISCARD_OWN],
    description:
      "Gain +2 Carrots. Look at the top card of ANY deck, you may discard it or put it back.",
  },
  {
    name: "Water Cooler",
    cost: {
      apples: 2,
      berries: 0,
      carrots: 2,
    },
    qty: 1,
    type: CARD_TYPE.Item,
    subtype: CARD_SUBTYPE.TOOL,
    tags: [],
    description:
      "Gain +2 Berries. Remove 2 Zzz counters in total from your Critters.",
  },
  {
    name: "Small Backpack",
    cost: {
      apples: 3,
      berries: 0,
      carrots: 3,
    },
    qty: 1,
    type: CARD_TYPE.Item,
    subtype: CARD_SUBTYPE.TOOL,
    tags: [TAGS.DISCARD_OWN, TAGS.CARD_DRAW, TAGS.TRASH],
    description: "Discard a card from hand to draw 2 cards.",
    buyBonus: "Trash a card from your discard pile.",
  },
  {
    name: "Convincing Disguise",
    cost: {
      apples: 0,
      berries: 3,
      carrots: 1,
    },
    qty: 1,
    type: CARD_TYPE.Item,
    subtype: CARD_SUBTYPE.TOOL,
    tags: [TAGS.CROP_GENERATION_RANDOM, TAGS.DISCARD_RIVAL_DECK],
    description:
      "Gain +3 of a random crop. Discard one of the top 3 cards of a Rival's deck.",
  },
  {
    name: "Watering Can",
    cost: {
      apples: 0,
      berries: 2,
      carrots: 2,
    },
    qty: 1,
    type: CARD_TYPE.Item,
    subtype: CARD_SUBTYPE.TOOL,
    tags: [TAGS.TOP_OF_DECK],
    description: "Put a card from your discard pile on top of your deck.",
    buyBonus: "Put this on top of your deck.",
  },
  {
    name: "Dustpan",
    cost: {
      apples: 1,
      berries: 2,
      carrots: 1,
    },
    qty: 1,
    type: CARD_TYPE.Item,
    subtype: CARD_SUBTYPE.TOOL,
    tags: [TAGS.CANTRIP, TAGS.REFUND, TAGS.REFUND_FROM_HAND, TAGS.REFRESH_SHOP],
    description: "Draw a card. You may Refund it this turn.",
    onDiscard: "Refresh a row in the shop.",
  },
  {
    name: "Knapsack",
    cost: {
      apples: 3,
      berries: 0,
      carrots: 1,
    },
    qty: 1,
    type: CARD_TYPE.Item,
    subtype: CARD_SUBTYPE.TOOL,
    tags: [TAGS.DISCARD_OWN, TAGS.CROP_STEAL],
    description:
      "Steal 2 crops from a Rival. You may discard a card from hand to steal 1 more.",
  },
  {
    name: "Compost Bin",
    cost: {
      apples: 1,
      berries: 3,
      carrots: 3,
    },
    qty: 1,
    type: CARD_TYPE.Item,
    subtype: CARD_SUBTYPE.TOOL,
    tags: [TAGS.DISCARD_OWN, TAGS.CROP_GENERATION_RANDOM],
    description: "Discard a card from hand to gain +2 of each crop.",
  },
  {
    name: "Toolbelt",
    cost: {
      apples: 1,
      berries: 2,
      carrots: 0,
    },
    qty: 1,
    type: CARD_TYPE.Item,
    subtype: CARD_SUBTYPE.TOOL,
    tags: [
      TAGS.SHUFFLE_CARDS,
      TAGS.TOOL_SYNERGY,
      TAGS.TOP_OF_DECK,
      TAGS.HOLDABLE,
    ],
    description:
      "Put a Tool from your discard pile on top of your deck. Holdable.",
    onDiscard: "Shuffle this into your deck.",
  },
  {
    name: "Trusty Trowel",
    cost: {
      apples: 2,
      berries: 1,
      carrots: 2,
    },
    qty: 1,
    type: CARD_TYPE.Item,
    subtype: CARD_SUBTYPE.TOOL,
    tags: [TAGS.CROP_GENERATION_RANDOM, TAGS.SEED_SYNERGY, TAGS.CARD_DRAW],
    description:
      "Gain +3 of a random crop. Put a Seed card from your discard pile into your hand.",
  },
  {
    name: "Dusty Broom",
    cost: {
      apples: 2,
      berries: 1,
      carrots: 0,
    },
    qty: 1,
    type: CARD_TYPE.Item,
    subtype: CARD_SUBTYPE.TOOL,
    tags: [TAGS.DISCOUNT, TAGS.SNATCH_DISCOUNT, TAGS.REFRESH_SHOP],
    description:
      "Discount once, Snatch the discounted crops from a card in the shop, then refresh that card.",
    buyBonus: "Discount once.",
  },
  {
    name: "Rat Food",
    cost: {
      apples: 3,
      berries: 1,
      carrots: 1,
    },
    qty: 1,
    type: CARD_TYPE.Item,
    subtype: CARD_SUBTYPE.TREAT,
    tags: [TAGS.CROP_GENERATION_APPLE, TAGS.REFRESH_SHOP],
    description: "Gain +3 Apples. Refresh 2 cards in the shop.",
  },
  {
    name: "Rabbit Food",
    cost: {
      apples: 1,
      berries: 1,
      carrots: 3,
    },
    qty: 1,
    type: CARD_TYPE.Item,
    subtype: CARD_SUBTYPE.TREAT,
    tags: [TAGS.CROP_GENERATION_CARROT, TAGS.ENERGY_RESTORE],
    description:
      "Gain +3 Carrots. Remove a Zzz counter from each of your Critters.",
  },
  {
    name: "Hog Food",
    cost: {
      apples: 1,
      berries: 3,
      carrots: 1,
    },
    qty: 1,
    type: CARD_TYPE.Item,
    subtype: CARD_SUBTYPE.TREAT,
    tags: [TAGS.CROP_GENERATION_BERRY, TAGS.TREAT_SYNERGY, TAGS.SHUFFLE_CARDS],
    description:
      "Gain +3 Berries. Shuffle a Treat from your discard pile back into your deck.",
  },
  {
    name: "Picnic Basket",
    cost: {
      apples: 2,
      berries: 3,
      carrots: 2,
    },
    qty: 1,
    type: CARD_TYPE.Item,
    subtype: CARD_SUBTYPE.TREAT,
    tags: [TAGS.CROP_GENERATION_ALL],
    description: "Gain +2 of a random crop. Gain +1 of each other crop.",
    onDiscard: "Gain +2 of each crop.",
  },
  {
    name: "Award Winning Crop",
    cost: {
      apples: 3,
      berries: 2,
      carrots: 2,
    },
    qty: 1,
    type: CARD_TYPE.Item,
    subtype: CARD_SUBTYPE.TREAT,
    tags: [TAGS.CROP_GENERATION_RANDOM],
    description: "Gain +5 of a random crop.",
  },
  {
    name: "Gift Basket",
    cost: {
      apples: 4,
      berries: 4,
      carrots: 4,
    },
    qty: 1,
    type: CARD_TYPE.Item,
    subtype: CARD_SUBTYPE.TREAT,
    tags: [TAGS.CROP_GENERATION_ALL],
    description: "Gain +2 of each crop.",
    buyBonus: "Each Rival gets +1 of each crop.",
  },
  {
    name: "Pot of Feed",
    cost: {
      apples: 3,
      berries: 3,
      carrots: 3,
    },
    qty: 1,
    type: CARD_TYPE.Item,
    subtype: CARD_SUBTYPE.TREAT,
    tags: [TAGS.ENERGY_RESTORE, TAGS.CARD_DRAW],
    description: "Draw 2 cards",
    buyBonus: "Remove a Zzz counter from each of your Critters.",
  },
  {
    name: "Midnight Snack",
    cost: {
      apples: 2,
      berries: 1,
      carrots: 1,
    },
    qty: 1,
    type: CARD_TYPE.Item,
    subtype: CARD_SUBTYPE.TREAT,
    tags: [TAGS.CROP_GENERATION_RANDOM, TAGS.CANTRIP],
    description: "Gain a random crop. Draw a card.",
    buyBonus: "Each player gets a random crop",
  },
  {
    name: "Pik'n'mix",
    cost: {
      apples: 0,
      berries: 3,
      carrots: 3,
    },
    qty: 1,
    type: CARD_TYPE.Item,
    subtype: CARD_SUBTYPE.TREAT,
    tags: [TAGS.CROP_GENERATION, TAGS.CROP_GENERATION_RANDOM],
    description: "Gain 3 random crops, then gain a crop of your choosing.",
  },
  {
    name: "Morning Cuppa'",
    cost: {
      apples: 1,
      berries: 2,
      carrots: 0,
    },
    qty: 1,
    type: CARD_TYPE.Item,
    subtype: CARD_SUBTYPE.TREAT,
    tags: [TAGS.ENERGY_RESTORE, TAGS.HOLDABLE],
    description: "Remove all Zzz counters from one of your Critters. Holdable",
    onDiscard: "Exhaust a Rival's Critter.",
  },
  {
    name: "Goodie Bag",
    cost: {
      apples: 2,
      berries: 2,
      carrots: 2,
    },
    qty: 1,
    type: CARD_TYPE.Item,
    subtype: CARD_SUBTYPE.TREAT,
    tags: [TAGS.CROP_GENERATION_RANDOM],
    description: "Gain 5 random crops. Each Rival gains a random crop.",
  },
  {
    name: "Plant Food",
    cost: {
      apples: 3,
      berries: 0,
      carrots: 3,
    },
    qty: 1,
    type: CARD_TYPE.Item,
    subtype: CARD_SUBTYPE.TREAT,
    tags: [TAGS.SEED_SYNERGY],
    description:
      "Harvest a Seed card from your discard pile as though it had 3 Sunlight. Holdable.",
  },
  {
    name: "Goldfish",
    cost: {
      apples: 0,
      berries: 2,
      carrots: 0,
    },
    qty: 1,
    type: CARD_TYPE.Item,
    subtype: CARD_SUBTYPE.GIFT,
    tags: [TAGS.GIFT],
    description: "This does nothing. Cannot be refunded.",
    buyBonus: "Gift this to a Rival.",
  },
  {
    name: "Birthday Present",
    cost: {
      apples: 0,
      berries: 0,
      carrots: 2,
    },
    qty: 1,
    type: CARD_TYPE.Item,
    subtype: CARD_SUBTYPE.GIFT,
    tags: [TAGS.GIFT, TAGS.CROP_GENERATION_RANDOM],
    description: "Gain 3 random crops. Gift this to a Rival.",
  },
  {
    name: "Hot Potato",
    cost: {
      apples: 2,
      berries: 0,
      carrots: 0,
    },
    qty: 1,
    type: CARD_TYPE.Item,
    subtype: CARD_SUBTYPE.GIFT,
    tags: [TAGS.GIFT, TAGS.CROP_DESTROY],
    description:
      "Destroy 2 of your crops to Gift this to a Rival. Cannot be Refunded.",
    buyBonus: "Gift this to a Rival.",
  },
  {
    name: "Rotten Crops",
    cost: {
      apples: 2,
      berries: 2,
      carrots: 2,
    },
    qty: 1,
    type: CARD_TYPE.Item,
    subtype: CARD_SUBTYPE.GIFT,
    tags: [TAGS.GIFT, TAGS.CROP_DESTROY],
    description: "Destroy 2 of your crops to draw a card. Cannot be Refunded.",
    buyBonus: "Gift this to a Rival",
  },
];

export default items;
