import { CARD_TYPE, ICard, TAGS } from "../models/cards.models";

const rabbits: ICard[] = [
  {
    name: "Carrot Grower",
    qty: 3,
    cost: {
      apples: 1,
      carrots: 4,
      berries: 1,
    },
    image: "carrot_grower",
    description: "Action: Gain 2 Carrots.",
    type: CARD_TYPE.Rabbit,
    energy: 3,
    tags: [TAGS.CRITTER, TAGS.GAIN_CROP_2],
  },
  {
    name: "Carrot Rancher",
    qty: 1,
    cost: {
      apples: 2,
      carrots: 6,
      berries: 2,
    },
    image: "carrot_rancher",
    description: "Action: Gain 3 Carrots.",
    type: CARD_TYPE.Rabbit,
    energy: 3,
    tags: [TAGS.CRITTER, TAGS.GAIN_CROP_3],
  },
  {
    name: "Apple Grower",
    qty: 3,
    cost: {
      apples: 4,
      carrots: 1,
      berries: 1,
    },
    image: "apple_grower",
    description: "Action: Gain 2 Apples.",
    type: CARD_TYPE.Rabbit,
    tags: [TAGS.CRITTER, TAGS.GAIN_CROP_2],
    energy: 3,
  },
  {
    name: "Apple Rancher",
    qty: 1,
    cost: {
      apples: 6,
      carrots: 2,
      berries: 2,
    },
    image: "apple_rancher",
    description: "Action: Gain 3 Apples.",
    type: CARD_TYPE.Rabbit,
    energy: 3,
    tags: [TAGS.CRITTER, TAGS.GAIN_CROP_3],
  },
  {
    name: "Berry Grower",
    qty: 3,
    cost: {
      apples: 1,
      carrots: 1,
      berries: 4,
    },
    image: "berry_grower",
    description: "Action: Gain 2 Berries.",
    type: CARD_TYPE.Rabbit,
    tags: [TAGS.CRITTER, TAGS.GAIN_CROP_2],
    energy: 3,
  },
  {
    name: "Berry Rancher",
    qty: 1,
    cost: {
      apples: 2,
      carrots: 2,
      berries: 6,
    },
    image: "berry_rancher",
    description: "Action: Gain 3 Berries.",
    type: CARD_TYPE.Rabbit,
    energy: 3,
    tags: [TAGS.CRITTER, TAGS.GAIN_CROP_3],
  },
  {
    name: "Agriculturist",
    qty: 2,
    cost: {
      apples: 3,
      berries: 3,
      carrots: 3,
    },
    image: "agriculturist",
    description: "Action: Gain 1 of each crop.",
    type: CARD_TYPE.Rabbit,
    tags: [TAGS.GAIN_CROP_3, TAGS.DIVERSE_CROPS],
    energy: 2,
  },
  {
    name: "Clodhopper",
    qty: 1,
    cost: {
      apples: 6,
      berries: 6,
      carrots: 6,
    },
    image: "clodhopper",
    description: "Action: Gain 2 of each crop.",
    type: CARD_TYPE.Rabbit,
    tags: [TAGS.GAIN_CROP_6, TAGS.DIVERSE_CROPS, TAGS.TITULAR],
    energy: 2,
  },
];

export default rabbits;
