import { CARD_TYPE, ICard } from "../models/cards.models";

const rewards: ICard[] = [
  {
    name: "",
    qty: 2,
    cost: {
      apples: 0,
      carrots: 0,
      berries: 0,
      any: 0,
    },
    image: "rummager",
    description: "The next card you buy is placed on top of your deck",
    type: CARD_TYPE.Reward,
    victoryPoints: 1,
  },
  {
    name: "",
    qty: 2,
    cost: {
      apples: 0,
      carrots: 0,
      berries: 0,
      any: 0,
    },
    image: "rummager",
    description: "Gain +1 of each crop",
    type: CARD_TYPE.Reward,
    victoryPoints: 1,
  },
  {
    name: "",
    qty: 2,
    cost: {
      apples: 0,
      carrots: 0,
      berries: 0,
      any: 0,
    },
    image: "rummager",
    description: "Gain +3 Berries",
    type: CARD_TYPE.Reward,
    victoryPoints: 1,
  },
  {
    name: "",
    qty: 2,
    cost: {
      apples: 0,
      carrots: 0,
      berries: 0,
      any: 0,
    },
    image: "rummager",
    description: "Gain +3 Carrots",
    type: CARD_TYPE.Reward,
    victoryPoints: 1,
  },
  {
    name: "",
    qty: 2,
    cost: {
      apples: 0,
      carrots: 0,
      berries: 0,
      any: 0,
    },
    image: "rummager",
    description: "Gain +3 Apples",
    type: CARD_TYPE.Reward,
    victoryPoints: 1,
  },
  {
    name: "",
    qty: 2,
    cost: {
      apples: 0,
      carrots: 0,
      berries: 0,
      any: 0,
    },
    image: "rummager",
    description: "Draw a card.",
    type: CARD_TYPE.Reward,
    victoryPoints: 1,
  },
  {
    name: "",
    qty: 2,
    cost: {
      apples: 0,
      carrots: 0,
      berries: 0,
      any: 0,
    },
    image: "rummager",
    description:
      "If you still have less VP than your competitor, draw another reward card.",
    type: CARD_TYPE.Reward,
    victoryPoints: 1,
  },
  {
    name: "",
    qty: 2,
    cost: {
      apples: 0,
      carrots: 0,
      berries: 0,
      any: 0,
    },
    image: "rummager",
    description: "Refund a card from your hand or discard pile",
    type: CARD_TYPE.Reward,
    victoryPoints: 1,
  },
  {
    name: "5 Star review",
    qty: 1,
    cost: {
      apples: 0,
      carrots: 0,
      berries: 0,
      any: 0,
    },
    image: "rummager",
    description: "",
    type: CARD_TYPE.Reward,
    victoryPoints: 2,
  },
  {
    name: "I.O.U",
    qty: 1,
    cost: {
      apples: 0,
      carrots: 0,
      berries: 0,
      any: 0,
    },
    image: "rummager",
    description: "When you complete your next task, draw an extra reward card.",
    type: CARD_TYPE.Reward,
    victoryPoints: 1,
  },
  {
    name: "Gift Card",
    qty: 1,
    cost: {
      apples: 0,
      carrots: 0,
      berries: 0,
      any: 0,
    },
    image: "rummager",
    description: "The next card you buy is free!",
    type: CARD_TYPE.Reward,
    victoryPoints: 1,
  },
  {
    name: "",
    qty: 1,
    cost: {
      apples: 0,
      carrots: 0,
      berries: 0,
      any: 0,
    },
    image: "rummager",
    description: "",
    type: CARD_TYPE.Reward,
    victoryPoints: 1,
  },
];

export default rewards;
