import { CARD_SET, CARD_TYPE, IWorkOrder } from "../models/cards.models";

const workOrders: IWorkOrder[] = [
  {
    name: "Apple Snack",
    qty: 2,
    cost: {
      apples: 0,
      berries: 1,
      carrots: 1,
    },
    crateCost: {
      apples: 1,
      berries: 0,
      carrots: 0,
    },
    crateAmount: 8,
    image: "/apple_snack.png",
    set: CARD_SET.BASE,
    type: CARD_TYPE.WorkOrder,
  },
  {
    name: "Berry Snack",
    qty: 2,
    cost: {
      apples: 1,
      berries: 0,
      carrots: 1,
    },
    crateCost: {
      apples: 0,
      berries: 1,
      carrots: 0,
    },
    crateAmount: 8,
    image: "berry_snack.png",
    set: CARD_SET.BASE,
    type: CARD_TYPE.WorkOrder,
  },
  {
    name: "Carrot Snack",
    qty: 2,
    cost: {
      apples: 1,
      berries: 1,
      carrots: 0,
    },
    crateCost: {
      apples: 0,
      berries: 0,
      carrots: 1,
    },
    crateAmount: 8,
    image: "carrot_snack.png",
    set: CARD_SET.BASE,
    type: CARD_TYPE.WorkOrder,
  },
  {
    name: "Apple Pie",
    qty: 3,
    cost: {
      apples: 1,
      berries: 1,
      carrots: 1,
    },
    crateCost: {
      apples: 1,
      berries: 1,
      carrots: 0,
    },
    crateAmount: 5,
    image: "apple_pie.png",
    set: CARD_SET.BASE,
    type: CARD_TYPE.WorkOrder,
  },
  {
    name: "Finger Food",
    qty: 3,
    cost: {
      apples: 1,
      berries: 1,
      carrots: 1,
    },
    crateCost: {
      apples: 0,
      berries: 1,
      carrots: 1,
    },
    crateAmount: 5,
    image: "finger_food.png",
    set: CARD_SET.BASE,
    type: CARD_TYPE.WorkOrder,
  },
  {
    name: "Apple-tiser",
    qty: 3,
    cost: {
      apples: 1,
      berries: 1,
      carrots: 1,
    },
    crateCost: {
      apples: 1,
      berries: 0,
      carrots: 1,
    },
    crateAmount: 5,
    image: "apple_tiser.png",
    set: CARD_SET.BASE,
    type: CARD_TYPE.WorkOrder,
  },
  {
    name: "Apple Craving",
    qty: 2,
    cost: {
      apples: 1,
      berries: 1,
      carrots: 1,
    },
    crateCost: {
      apples: 2,
      berries: 0,
      carrots: 0,
    },
    crateAmount: 5,
    image: "apple_craving.png",
    set: CARD_SET.BASE,
    type: CARD_TYPE.WorkOrder,
  },
  {
    name: "Berry Craving",
    qty: 2,
    cost: {
      apples: 1,
      berries: 1,
      carrots: 1,
    },
    crateCost: {
      apples: 0,
      berries: 2,
      carrots: 0,
    },
    crateAmount: 5,
    image: "berry_craving.png",
    set: CARD_SET.BASE,
    type: CARD_TYPE.WorkOrder,
  },
  {
    name: "Carrot Craving",
    qty: 2,
    cost: {
      apples: 1,
      berries: 1,
      carrots: 1,
    },
    crateCost: {
      apples: 0,
      berries: 0,
      carrots: 2,
    },
    crateAmount: 5,
    image: "carrot_craving.png",
    set: CARD_SET.BASE,
    type: CARD_TYPE.WorkOrder,
  },
  {
    name: "Ample Apples",
    qty: 1,
    cost: {
      apples: 2,
      berries: 1,
      carrots: 1,
    },
    crateCost: {
      apples: 3,
      berries: 0,
      carrots: 0,
    },
    crateAmount: 4,
    image: "ample_apples.png",
    set: CARD_SET.BASE,
    type: CARD_TYPE.WorkOrder,
  },
  {
    name: "Berry Buffet",
    qty: 1,
    cost: {
      apples: 1,
      berries: 2,
      carrots: 1,
    },
    crateCost: {
      apples: 0,
      berries: 3,
      carrots: 0,
    },
    crateAmount: 4,
    image: "berry_buffet.png",
    set: CARD_SET.BASE,
    type: CARD_TYPE.WorkOrder,
  },
  {
    name: "Carrot Cache",
    qty: 1,
    cost: {
      apples: 1,
      berries: 1,
      carrots: 2,
    },
    crateCost: {
      apples: 0,
      berries: 0,
      carrots: 3,
    },
    crateAmount: 4,
    image: "carrot_cache.png",
    set: CARD_SET.BASE,
    type: CARD_TYPE.WorkOrder,
  },
  {
    name: "Apple Crumble",
    qty: 1,
    cost: {
      apples: 2,
      berries: 1,
      carrots: 1,
    },
    crateCost: {
      apples: 2,
      berries: 1,
      carrots: 0,
    },
    crateAmount: 4,
    image: "apple_crumble.png",
    set: CARD_SET.BASE,
    type: CARD_TYPE.WorkOrder,
  },
  {
    name: "Big Brekkie",
    qty: 1,
    cost: {
      apples: 2,
      berries: 1,
      carrots: 1,
    },
    crateCost: {
      apples: 2,
      berries: 0,
      carrots: 1,
    },
    crateAmount: 4,
    image: "big_brekkie.png",
    set: CARD_SET.BASE,
    type: CARD_TYPE.WorkOrder,
  },
  {
    name: "Fruit Salad",
    qty: 1,
    cost: {
      apples: 1,
      berries: 2,
      carrots: 1,
    },
    crateCost: {
      apples: 1,
      berries: 2,
      carrots: 0,
    },
    crateAmount: 4,
    image: "fruit_salad.png",
    set: CARD_SET.BASE,
    type: CARD_TYPE.WorkOrder,
  },
  {
    name: "Second Breakfast",
    qty: 1,
    cost: {
      apples: 1,
      berries: 2,
      carrots: 1,
    },
    crateCost: {
      apples: 0,
      berries: 2,
      carrots: 1,
    },
    crateAmount: 4,
    image: "second_breakfast.png",
    set: CARD_SET.BASE,
    type: CARD_TYPE.WorkOrder,
  },
  {
    name: "Farm Lunch",
    qty: 1,
    cost: {
      apples: 1,
      berries: 1,
      carrots: 2,
    },
    crateCost: {
      apples: 1,
      berries: 0,
      carrots: 2,
    },
    crateAmount: 4,
    image: "farm_lunch.png",
    set: CARD_SET.BASE,
    type: CARD_TYPE.WorkOrder,
  },
  {
    name: "Carrot Cake",
    qty: 1,
    cost: {
      apples: 1,
      berries: 1,
      carrots: 2,
    },
    crateCost: {
      apples: 0,
      berries: 1,
      carrots: 2,
    },
    crateAmount: 4,
    image: "carrot_cake.png",
    set: CARD_SET.BASE,
    type: CARD_TYPE.WorkOrder,
  },
  {
    name: "Smorgasbord",
    image: "/smorgasbord.png",
    qty: 3,
    cost: {
      apples: 2,
      berries: 2,
      carrots: 2,
    },
    crateCost: {
      apples: 1,
      berries: 1,
      carrots: 1,
    },
    crateAmount: 4,
    set: CARD_SET.CROWD_FUND,
    type: CARD_TYPE.WorkOrder,
  },
  {
    name: "Apple Fundraiser",
    image: "/apple_fundraiser.png",
    qty: 1,
    cost: {
      apples: 2,
      berries: 2,
      carrots: 2,
    },
    crateCost: {
      apples: 3,
      berries: 1,
      carrots: 1,
    },
    crateAmount: 3,
    set: CARD_SET.CROWD_FUND,
    type: CARD_TYPE.WorkOrder,
  },
  {
    name: "Berry Fundraiser",
    image: "/berry_fundraiser.png",
    qty: 1,
    cost: {
      apples: 2,
      berries: 2,
      carrots: 2,
    },
    crateCost: {
      apples: 3,
      berries: 1,
      carrots: 1,
    },
    crateAmount: 3,
    set: CARD_SET.CROWD_FUND,
    type: CARD_TYPE.WorkOrder,
  },
  {
    name: "Carrot Fundraiser",
    image: "/carrot_fundraiser.png",
    qty: 1,
    cost: {
      apples: 2,
      berries: 2,
      carrots: 2,
    },
    crateCost: {
      apples: 1,
      berries: 1,
      carrots: 3,
    },
    crateAmount: 3,
    set: CARD_SET.CROWD_FUND,
    type: CARD_TYPE.WorkOrder,
  },
];

export default workOrders;
