import { CARD_SET, CARD_TYPE, IWorkOrder } from "../models/cards.models";

const workOrders: IWorkOrder[] = [
  {
    name: "Apple Snack",
    qty: 2,
    cost: {
      apples: 2,
      berries: 2,
      carrots: 2,
    },
    crateCost: {
      apples: 1,
      berries: 0,
      carrots: 0,
    },
    crateAmount: 8,
    image: "",
    set: CARD_SET.BASE,
    type: CARD_TYPE.WorkOrder,
  },
  {
    name: "Berry Snack",
    qty: 2,
    cost: {
      apples: 2,
      berries: 2,
      carrots: 2,
    },
    crateCost: {
      apples: 0,
      berries: 1,
      carrots: 0,
    },
    crateAmount: 8,
    image: "",
    set: CARD_SET.BASE,
    type: CARD_TYPE.WorkOrder,
  },
  {
    name: "Carrot Snack",
    qty: 2,
    cost: {
      apples: 2,
      berries: 2,
      carrots: 2,
    },
    crateCost: {
      apples: 0,
      berries: 0,
      carrots: 1,
    },
    crateAmount: 8,
    image: "",
    set: CARD_SET.BASE,
    type: CARD_TYPE.WorkOrder,
  },
  {
    name: "Apple Pie",
    qty: 3,
    cost: {
      apples: 2,
      berries: 2,
      carrots: 2,
    },
    crateCost: {
      apples: 1,
      berries: 1,
      carrots: 0,
    },
    crateAmount: 5,
    image: "",
    set: CARD_SET.BASE,
    type: CARD_TYPE.WorkOrder,
  },
  {
    name: "Finger Food",
    qty: 3,
    cost: {
      apples: 2,
      berries: 2,
      carrots: 2,
    },
    crateCost: {
      apples: 0,
      berries: 1,
      carrots: 1,
    },
    crateAmount: 5,
    image: "",
    set: CARD_SET.BASE,
    type: CARD_TYPE.WorkOrder,
  },
  {
    name: "Apple-tiser",
    qty: 3,
    cost: {
      apples: 2,
      berries: 2,
      carrots: 2,
    },
    crateCost: {
      apples: 1,
      berries: 0,
      carrots: 1,
    },
    crateAmount: 5,
    image: "",
    set: CARD_SET.BASE,
    type: CARD_TYPE.WorkOrder,
  },
  {
    name: "Apple Craving",
    qty: 2,
    cost: {
      apples: 2,
      berries: 2,
      carrots: 2,
    },
    crateCost: {
      apples: 2,
      berries: 0,
      carrots: 0,
    },
    crateAmount: 5,
    image: "",
    set: CARD_SET.BASE,
    type: CARD_TYPE.WorkOrder,
  },
  {
    name: "Berry Craving",
    qty: 2,
    cost: {
      apples: 2,
      berries: 2,
      carrots: 2,
    },
    crateCost: {
      apples: 0,
      berries: 2,
      carrots: 0,
    },
    crateAmount: 5,
    image: "",
    set: CARD_SET.BASE,
    type: CARD_TYPE.WorkOrder,
  },
  {
    name: "Carrot Craving",
    qty: 2,
    cost: {
      apples: 2,
      berries: 2,
      carrots: 2,
    },
    crateCost: {
      apples: 0,
      berries: 0,
      carrots: 2,
    },
    crateAmount: 5,
    image: "",
    set: CARD_SET.BASE,
    type: CARD_TYPE.WorkOrder,
  },
  {
    name: "Ample Apples",
    qty: 1,
    cost: {
      apples: 2,
      berries: 2,
      carrots: 2,
    },
    crateCost: {
      apples: 3,
      berries: 0,
      carrots: 0,
    },
    crateAmount: 4,
    image: "",
    set: CARD_SET.BASE,
    type: CARD_TYPE.WorkOrder,
  },
  {
    name: "Berry Buffet",
    qty: 1,
    cost: {
      apples: 2,
      berries: 2,
      carrots: 2,
    },
    crateCost: {
      apples: 0,
      berries: 3,
      carrots: 0,
    },
    crateAmount: 4,
    image: "",
    set: CARD_SET.BASE,
    type: CARD_TYPE.WorkOrder,
  },
  {
    name: "Carrot Cache",
    qty: 1,
    cost: {
      apples: 2,
      berries: 2,
      carrots: 2,
    },
    crateCost: {
      apples: 0,
      berries: 0,
      carrots: 3,
    },
    crateAmount: 4,
    image: "",
    set: CARD_SET.BASE,
    type: CARD_TYPE.WorkOrder,
  },
  {
    name: "Apple Crumble",
    qty: 1,
    cost: {
      apples: 2,
      berries: 2,
      carrots: 2,
    },
    crateCost: {
      apples: 2,
      berries: 1,
      carrots: 0,
    },
    crateAmount: 4,
    image: "",
    set: CARD_SET.BASE,
    type: CARD_TYPE.WorkOrder,
  },
  {
    name: "Big Brekkie",
    qty: 1,
    cost: {
      apples: 2,
      berries: 2,
      carrots: 2,
    },
    crateCost: {
      apples: 2,
      berries: 0,
      carrots: 1,
    },
    crateAmount: 4,
    image: "",
    set: CARD_SET.BASE,
    type: CARD_TYPE.WorkOrder,
  },
  {
    name: "Fruit Salad",
    qty: 1,
    cost: {
      apples: 2,
      berries: 2,
      carrots: 2,
    },
    crateCost: {
      apples: 1,
      berries: 2,
      carrots: 0,
    },
    crateAmount: 4,
    image: "",
    set: CARD_SET.BASE,
    type: CARD_TYPE.WorkOrder,
  },
  {
    name: "Second Breakfast",
    qty: 1,
    cost: {
      apples: 2,
      berries: 2,
      carrots: 2,
    },
    crateCost: {
      apples: 0,
      berries: 2,
      carrots: 1,
    },
    crateAmount: 4,
    image: "",
    set: CARD_SET.BASE,
    type: CARD_TYPE.WorkOrder,
  },
  {
    name: "Farm Lunch",
    qty: 1,
    cost: {
      apples: 2,
      berries: 2,
      carrots: 2,
    },
    crateCost: {
      apples: 1,
      berries: 0,
      carrots: 2,
    },
    crateAmount: 4,
    image: "",
    set: CARD_SET.BASE,
    type: CARD_TYPE.WorkOrder,
  },
  {
    name: "Carrot Cake",
    qty: 1,
    cost: {
      apples: 2,
      berries: 2,
      carrots: 2,
    },
    crateCost: {
      apples: 0,
      berries: 1,
      carrots: 2,
    },
    crateAmount: 4,
    image: "",
    set: CARD_SET.BASE,
    type: CARD_TYPE.WorkOrder,
  },
  {
    name: "Smorgasbord",
    qty: 3,
    cost: {
      apples: 1,
      berries: 1,
      carrots: 1,
    },
    crateCost: {
      apples: 1,
      berries: 1,
      carrots: 1,
    },
    crateAmount: 5,
    image: "",
    set: CARD_SET.CROWD_FUND,
    type: CARD_TYPE.WorkOrder,
  },
  {
    name: "Apple Fundraiser",
    qty: 1,
    cost: {
      apples: 3,
      berries: 2,
      carrots: 2,
    },
    crateCost: {
      apples: 3,
      berries: 1,
      carrots: 1,
    },
    crateAmount: 3,
    image: "",
    set: CARD_SET.CROWD_FUND,
    type: CARD_TYPE.WorkOrder,
  },
  {
    name: "Berry Fundraiser",
    qty: 1,
    cost: {
      apples: 2,
      berries: 3,
      carrots: 2,
    },
    crateCost: {
      apples: 3,
      berries: 1,
      carrots: 1,
    },
    crateAmount: 3,
    image: "",
    set: CARD_SET.CROWD_FUND,
    type: CARD_TYPE.WorkOrder,
  },
  {
    name: "Carrot Fundraiser",
    qty: 1,
    cost: {
      apples: 2,
      berries: 2,
      carrots: 3,
    },
    crateCost: {
      apples: 1,
      berries: 1,
      carrots: 3,
    },
    crateAmount: 3,
    image: "",
    set: CARD_SET.CROWD_FUND,
    type: CARD_TYPE.WorkOrder,
  },
];

export default workOrders;
